FROM python:3.7-slim-stretch

RUN apt update && apt install -y git
WORKDIR /opt 
RUN git clone https://github.com/sp2ong/HBmonitor.git 

RUN cd HBmonitor && chmod +x install.sh && \
./install.sh
COPY config_SAMPLE.py /opt/HBmonitor/config.py

EXPOSE 80/tcp

WORKDIR /opt/HBmonitor
CMD python3 monitor.py 
