version: "3"
services:
  hblink3:
    build:
      context: .
      dockerfile: Dockerfile.hblink3
    container_name: hblink3
    restart: unless-stopped
    network_mode: host
    ports:
     - "62030:62030/udp"
     - "62031:62031/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dmr/hblink.cfg:/config/hblink.cfg  
      - ./dmr/peer_ids.json:/config/peer_ids.json  
      - ./dmr/rules.py:/config/rules.py  
      - ./dmr/subscriber_ids.json:/config/subscriber_ids.json


  hbmonitor:
    build:
      context: .
      dockerfile: Dockerfile.hbmon
    container_name: hbmon
    restart: unless-stopped
    network_mode: host
    ports:
     - "8081:8080"
     - "9000:9000"
    volumes:
      - ./dmr/config_hbmonitor.py:/opt/HBmonitor/config.py
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - hblink3


